### ISSUE TITLE
Show System data

### ISSUE THREAD

**Issue by PragTob** [PragTob/benchee_html#25]
Part of the `Benchee` Suite is `system` data including information about CPU, Memory, OS, Elixir and Erlang version.

We already display the Elixir and Erlang version on the top right. It'd be nice to add the other information as well. The top right isn't big enough for it so we'd need another place.

As it's part of the main content I'd suggest another panel with that information perhaps as a table or something else. Not entirely sure tbh.

Also not sure if that panel should come first or last or where it should appear. In the console formatter that information comes first but only because we can get it right away, I think the benchmark results are still most important :)

**Comment by PragTob** [comment]
@devonestes any feelings about this? :D

**Comment by devonestes** [comment]
I think this is a great idea since the system information and exact data you're getting about the benchmarks will be highly correlated.

This might be some sort of Stockholm syndrome talking since I've had to work on ~1,000,000 JavaScript tooltips recently, but maybe a JavaScript tooltip would work? We could have a link (maybe in the top right as it is now) that you can hover over and see the system information pop up?

**Comment by PragTob** [comment]
Interesting idea, I'd feel like that'd devalue the system information (as it's moved from the main content part to a mere tooltip) though. As you mention, they are highly correlated.

I think I'd somehow prefer for it to be part of the main content or at least to not be hidden in tooltip - I like to use those more for explaining what a given metric means or why something is shown (explanations).
